<?php
Route::get('/','Home\Index@index')->middleware('guest');
Route::group(['prefix'=>'home','namespace'=>'Home'],function (){
    Route::any('login','Login@login');
    Route::get('logout','Login@logout');
    Route::get('download','Login@download');
    Route::any('register','Register@register');
    Route::post('registerVerify','Register@registerVerify');
    Route::any('forget','ForgetPassword@forgetPassword');
    Route::post('forgetVerify','ForgetPassword@forgetVerify');
});

Route::group(['prefix'=>'home','namespace'=>'Home','middleware'=>'guest'],function (){
    Route::get('index','Index@index');
    Route::get('qiandao','Index@qiandao');
    Route::post('rent','Index@rent');
    Route::get('member','Member@member');
    Route::any('reset','Member@resetPassword');
    Route::get('link','Member@link');
    Route::get('team','Member@team');
    Route::get('qrcode/{url}','Member@qrcode');
    Route::get('notice','Member@notice');
    Route::get('noticePreview/{id}','Member@noticePreview');
    Route::get('memberService','Member@memberService');
    Route::any('realNameAuth','Member@realNameAuth');
    Route::get('bill','Member@bill');
    Route::get('unprocessedOrder','Member@unprocessedOrder');
    Route::get('record','Member@record');
    Route::get('orderPreview/{id}','Member@orderPreview');
    Route::get('tradeComplaint/{orderId}','Member@tradeComplaint');
    Route::post('finishPay','Member@finishPay');
    Route::post('finishPayConfirm','Member@finishPayConfirm');
    Route::get('quotations','Member@quotations');
    Route::any('ideal','Member@ideal');
    Route::get('idCardCheck/{idCard}','Member@idCardCheck');
    Route::get('running','MyMiner@running');
    Route::post('collect','MyMiner@collect');
    Route::get('finished','MyMiner@finished');
    Route::get('getMoreMinerFinished/{offset}','MyMiner@getMoreMinerFinished');
    Route::get('buy','Trade@buy');
    Route::get('tradeCenter','Trade@tradeCenter');
    Route::post('tradeBuy','Trade@tradeBuy');
    Route::post('tradeSales','Trade@tradeSales');
    Route::post('tradeCheck','Trade@tradeCheck');
    Route::get('paidan/{number}','Trade@paidan');
    Route::get('cancelOrder/{orderId}','Trade@cancelOrder');
});
